### ISSUE TITLE
French Subdivision holidays missing descriptions

### ISSUE THREAD

**Issue by XSpielinbox** [focus-shift/jollyday#553]
### More information

Most holidays of subdivisions in France, e.g. the 10th of June in Guyane are missing descriptions.

**Comment by derTobsch** [comment]
Hey @XSpielinbox,
I just took a quick look and I would say that not only the descriptions are missing but also the subdivisions are wrong? Should they not be like here, https://de.wikipedia.org/wiki/ISO_3166-2:FR, since 2016?

[Auvergne-Rhône-Alpes](https://de.wikipedia.org/wiki/Auvergne-Rh%C3%B4ne-Alpes) 	FR-ARA
[Bourgogne-Franche-Comté](https://de.wikipedia.org/wiki/Bourgogne-Franche-Comt%C3%A9) 	FR-BFC
[Bretagne](https://de.wikipedia.org/wiki/Bretagne) 	FR-BRE
[Centre-Val de Loire](https://de.wikipedia.org/wiki/Centre-Val_de_Loire) 	FR-CVL
[Grand Est](https://de.wikipedia.org/wiki/Grand_Est) 	FR-GES
[Hauts-de-France](https://de.wikipedia.org/wiki/Hauts-de-France) 	FR-HDF
[Île-de-France](https://de.wikipedia.org/wiki/%C3%8Ele-de-France) 	FR-IDF
[Normandie](https://de.wikipedia.org/wiki/Normandie) 	FR-NOR
[Nouvelle-Aquitaine](https://de.wikipedia.org/wiki/Nouvelle-Aquitaine) 	FR-NAQ
[Okzitanien](https://de.wikipedia.org/wiki/Okzitanien_(Verwaltungsregion)) 	FR-OCC
[Pays de la Loire](https://de.wikipedia.org/wiki/Pays_de_la_Loire) 	FR-PDL
[Provence-Alpes-Côte d’Azur](https://de.wikipedia.org/wiki/Provence-Alpes-C%C3%B4te_d%E2%80%99Azur) 	FR-PAC

And also the Départements are no longer written with numbers.
